---
- name: Test Playbook
  hosts: all
  gather_facts: false
  remote_user: ansibler

  tasks:
    - name: Set PWR LED trigger to timer
      ansible.builtin.shell: echo timer | sudo tee /sys/devices/platform/leds/leds/PWR/trigger

    - name: Copy service unit
      ansible.builtin.copy:
        src: meals.service
        dest: /etc/systemd/system/meals.service
        owner: root
        group: root
        mode: 0644
      register: service_unit
    
    - name: Reload systemd units
      ansible.builtin.shell: sudo systemctl daemon-reload
      when: service_unit.changed

    - name: Stop service
      ansible.builtin.shell: sudo systemctl stop meals.service

    - name: Clone this repo
      ansible.builtin.git:
        repo: git@github.com:pmerlo/meals.git
        dest: /home/ansibler/meals
        key_file: /home/ansibler/.ssh/id_rsa_meals
        accept_hostkey: yes
        force: yes

    - name: Clone frontend dist repo
      ansible.builtin.git:
        repo: git@github.com:pmerlo/meals-dist.git
        dest: /home/ansibler/meals/frontend-dist
        key_file: /home/ansibler/.ssh/id_rsa_meals_dist
        accept_hostkey: yes
        force: yes

    - name: Build containers
      ansible.builtin.shell: docker compose --file /home/ansibler/meals/docker-compose.yml build

    - name: Start service
      ansible.builtin.shell: sudo systemctl start meals.service

    - name: Set PWR LED trigger to default-on
      ansible.builtin.shell: echo default-on | sudo tee /sys/devices/platform/leds/leds/PWR/trigger
