version: '3.9'

services:
  mongo:
    image: mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - 3000:3000

  frontend:
    build: ./frontend-dist
    depends_on:
      - backend
    ports:
      - 80:80

volumes:
  mongo_data:
